In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import accuracy_score

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier
from sklearn.metrics import mean_squared_error, r2_score, classification_report
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import warnings
warnings.filterwarnings('ignore')

In [5]:
data=r"C:\Users\Asus\OneDrive\Desktop\Machine learning\Business_Profit.csv"
df=pd.read_csv(data)

In [ ]:
df.head()

In [7]:
df.tail()

    Marketing Spend  Administration  Transport     Area    Profit
45          1000.23       124153.04    1903.93    Dhaka  64926.08
46          1315.46       115816.21  297114.46  Rangpur  49490.75
47             0.00       135426.92       0.00      Ctg  42559.73
48           542.05        51743.15       0.00    Dhaka  35673.41
49             0.00       116983.80   45173.06      Ctg  14681.40

In [8]:
df.info

<bound method DataFrame.info of     Marketing Spend  Administration  Transport     Area     Profit
0         114523.61       136897.80  471784.10    Dhaka  192261.83
1         162597.70       151377.59  443898.53      Ctg  191792.06
2         153441.51       101145.55  407934.54  Rangpur  191050.39
3         144372.41       118671.85  383199.62    Dhaka  182901.99
4         142107.34        91391.77  366168.42  Rangpur  166187.94
5         131876.90        99814.71  362861.36    Dhaka  156991.12
6         134615.46       147198.87  127716.82      Ctg  156122.51
7         130298.13       145530.06  323876.68  Rangpur  155752.60
8         120542.52       148718.95  311613.29    Dhaka  152211.77
9         123334.88       108679.17  304981.62      Ctg  149759.96
10        101913.08       110594.11  229160.95  Rangpur  146121.95
11        100671.96        91790.61  249744.55      Ctg  144259.40
12         93863.75       127320.38  249839.44  Rangpur  141585.52
13         91992.39       135495.07  252664.93      Ctg  134307.35
14        119943.24       156547.42  255612.92  Rangpur  132602.65
15        165349.20       122616.84  261776.23    Dhaka  129917.04
16         78013.11       121597.55  264346.06      Ctg  125370.93
17         94657.16       145077.58  282574.31    Dhaka  125370.93
18         91749.16       114175.79  294919.57  Rangpur  124266.90
19         86419.70       153514.11       0.00    Dhaka  122776.86
20         76253.86       113867.30  298664.47      Ctg  118474.03
21         78389.47       153773.43  299737.29    Dhaka  111313.02
22         73994.56       122782.75  303319.26  Rangpur  110353.29
23         67532.53       105751.03  304768.73  Rangpur  108733.99
24         77044.01        99281.34  140574.81    Dhaka  108552.04
25         64664.71       139553.16  137962.62      Ctg  107404.34
26         75328.87       144135.98  134050.07  Rangpur  107533.54
27         72107.60       127864.55  353183.81    Dhaka  105008.31
28         66051.52       182645.56  118148.20  Rangpur  103282.38
29         65605.48       153032.06  107138.38    Dhaka  101004.64
30         61994.48       115641.28   91131.24  Rangpur   99937.59
31         61136.38       152701.92   88218.23    Dhaka   97483.56
32         63408.86       129219.61   46085.25      Ctg   97427.84
33         55493.95       103057.49  214634.81  Rangpur   96778.92
34         46426.07       157693.92  210797.67      Ctg   96712.80
35         46014.02        85047.44  205517.64    Dhaka   96479.51
36         28663.76       127056.21  201126.82  Rangpur   90708.19
37         44069.95        51283.14  197029.42      Ctg   89949.14
38         20229.59        65947.93  185265.10    Dhaka   81229.56
39         38558.51        82982.09  174999.30      Ctg   81005.76
40         28754.33       118546.05  172795.67      Ctg   78239.91
41         27892.92        84710.77  164470.71  Rangpur   77798.83
42         23640.93        96189.63  148001.11      Ctg   71498.49
43         15505.73       127382.30   35534.17    Dhaka   69758.98
44         22177.74       154806.14   28334.72      Ctg   65200.33
45          1000.23       124153.04    1903.93    Dhaka   64926.08
46          1315.46       115816.21  297114.46  Rangpur   49490.75
47             0.00       135426.92       0.00      Ctg   42559.73
48           542.05        51743.15       0.00    Dhaka   35673.41
49             0.00       116983.80   45173.06      Ctg   14681.40>

In [9]:
df.isnull().sum()

Marketing Spend    0
Administration     0
Transport          0
Area               0
Profit             0
dtype: int64

In [10]:
df.columns

Index(['Marketing Spend', 'Administration', 'Transport', 'Area', 'Profit'], dtype='object')

In [13]:
x=df.drop(['Profit'],axis=1)

In [14]:
x.head()

   Marketing Spend  Administration  Transport     Area
0        114523.61       136897.80  471784.10    Dhaka
1        162597.70       151377.59  443898.53      Ctg
2        153441.51       101145.55  407934.54  Rangpur
3        144372.41       118671.85  383199.62    Dhaka
4        142107.34        91391.77  366168.42  Rangpur

In [16]:
y=df['Profit']

In [17]:
y.head()

0    192261.83
1    191792.06
2    191050.39
3    182901.99
4    166187.94
Name: Profit, dtype: float64

In [18]:
city=pd.get_dummies(x['Area'],drop_first=True)

In [19]:
city.head()

   Dhaka  Rangpur
0   True    False
1  False    False
2  False     True
3   True    False
4  False     True

In [20]:
x=x.drop('Area',axis=1)

In [21]:
x.head()

   Marketing Spend  Administration  Transport
0        114523.61       136897.80  471784.10
1        162597.70       151377.59  443898.53
2        153441.51       101145.55  407934.54
3        144372.41       118671.85  383199.62
4        142107.34        91391.77  366168.42

In [22]:
x=pd.concat([x,city],axis=1)

In [23]:
x.head()

   Marketing Spend  Administration  Transport  Dhaka  Rangpur
0        114523.61       136897.80  471784.10   True    False
1        162597.70       151377.59  443898.53  False    False
2        153441.51       101145.55  407934.54  False     True
3        144372.41       118671.85  383199.62   True    False
4        142107.34        91391.77  366168.42  False     True

In [24]:
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size = 0.25, random_state = 0)

In [25]:
xtrain

    Marketing Spend  Administration  Transport  Dhaka  Rangpur
34         46426.07       157693.92  210797.67  False    False
18         91749.16       114175.79  294919.57  False     True
7         130298.13       145530.06  323876.68  False     True
14        119943.24       156547.42  255612.92  False     True
45          1000.23       124153.04    1903.93   True    False
48           542.05        51743.15       0.00   True    False
29         65605.48       153032.06  107138.38   True    False
15        165349.20       122616.84  261776.23   True    False
30         61994.48       115641.28   91131.24  False     True
32         63408.86       129219.61   46085.25  False    False
16         78013.11       121597.55  264346.06  False    False
42         23640.93        96189.63  148001.11  False    False
20         76253.86       113867.30  298664.47  False    False
43         15505.73       127382.30   35534.17   True    False
8         120542.52       148718.95  311613.29   True    False
13         91992.39       135495.07  252664.93  False    False
25         64664.71       139553.16  137962.62  False    False
5         131876.90        99814.71  362861.36   True    False
17         94657.16       145077.58  282574.31   True    False
40         28754.33       118546.05  172795.67  False    False
49             0.00       116983.80   45173.06  False    False
1         162597.70       151377.59  443898.53  False    False
12         93863.75       127320.38  249839.44  False     True
37         44069.95        51283.14  197029.42  False    False
24         77044.01        99281.34  140574.81   True    False
6         134615.46       147198.87  127716.82  False    False
23         67532.53       105751.03  304768.73  False     True
36         28663.76       127056.21  201126.82  False     True
21         78389.47       153773.43  299737.29   True    False
19         86419.70       153514.11       0.00   True    False
9         123334.88       108679.17  304981.62  False    False
39         38558.51        82982.09  174999.30  False    False
46          1315.46       115816.21  297114.46  False     True
3         144372.41       118671.85  383199.62   True    False
0         114523.61       136897.80  471784.10   True    False
47             0.00       135426.92       0.00  False    False
44         22177.74       154806.14   28334.72  False    False

In [47]:
ytest

28    103282.38
11    144259.40
10    146121.95
41     77798.83
2     191050.39
27    105008.31
38     81229.56
31     97483.56
22    110353.29
4     166187.94
33     96778.92
35     96479.51
26    107533.54
Name: Profit, dtype: float64

In [26]:
xtest

    Marketing Spend  Administration  Transport  Dhaka  Rangpur
28         66051.52       182645.56  118148.20  False     True
11        100671.96        91790.61  249744.55  False    False
10        101913.08       110594.11  229160.95  False     True
41         27892.92        84710.77  164470.71  False     True
2         153441.51       101145.55  407934.54  False     True
27         72107.60       127864.55  353183.81   True    False
38         20229.59        65947.93  185265.10   True    False
31         61136.38       152701.92   88218.23   True    False
22         73994.56       122782.75  303319.26  False     True
4         142107.34        91391.77  366168.42  False     True
33         55493.95       103057.49  214634.81  False     True
35         46014.02        85047.44  205517.64   True    False
26         75328.87       144135.98  134050.07  False     True

In [29]:
scaler=StandardScaler()
x_train_scaled=scaler.fit_transform(xtrain)

In [30]:
x_train_scaled

array([[-0.550107  ,  1.29442491,  0.05686334, -0.73598007, -0.52522573],
       [ 0.39903705, -0.39835003,  0.71487094, -0.73598007,  1.90394328],
       [ 1.20631929,  0.82127321,  0.94137556, -0.73598007,  1.90394328],
       [ 0.98946994,  1.24982818,  0.40741147, -0.73598007,  1.90394328],
       [-1.50140282, -0.01025342, -1.57711865,  1.35873244, -0.52522573],
       [-1.5109979 , -2.8268645 , -1.59201133,  1.35873244, -0.52522573],
       [-0.14845692,  1.11308716, -0.75396715,  1.35873244, -0.52522573],
       [ 1.94034944, -0.07000876,  0.45562133,  1.35873244, -0.52522573],
       [-0.22407752, -0.34134517, -0.87917616, -0.73598007,  1.90394328],
       [-0.19445795,  0.18682681, -1.23152916, -0.73598007, -0.52522573],
       [ 0.11138036, -0.10965726,  0.47572273, -0.73598007, -0.52522573],
       [-1.02726732, -1.09797846, -0.43433591, -0.73598007, -0.52522573],
       [ 0.07453861, -0.41034972,  0.74416382, -0.73598007, -0.52522573],
       [-1.19763251,  0.11535884, -1.31406048,  1.35873244, -0.52522573],
       [ 1.00201991,  0.94531515,  0.84545043,  1.35873244, -0.52522573],
       [ 0.40413071,  0.43093062,  0.38435208, -0.73598007, -0.52522573],
       [-0.16815827,  0.58878283, -0.51285771, -0.73598007, -0.52522573],
       [ 1.23938147, -0.95696954,  1.24631655,  1.35873244, -0.52522573],
       [ 0.45993561,  0.80367257,  0.61830542,  1.35873244, -0.52522573],
       [-0.92018386, -0.22835498, -0.24039106, -0.73598007, -0.52522573],
       [-1.52234937, -0.28912362, -1.23866438, -0.73598007, -0.52522573],
       [ 1.88272826,  1.04873133,  1.88019517, -0.73598007, -0.52522573],
       [ 0.44332023,  0.11295026,  0.36225089, -0.73598007,  1.90394328],
       [-0.59944824, -2.84475804, -0.05083291, -0.73598007, -0.52522573],
       [ 0.09108572, -0.97771665, -0.49242497,  1.35873244, -0.52522573],
       [ 1.29673166,  0.88618684, -0.5930011 , -0.73598007, -0.52522573],
       [-0.10810115, -0.72605764,  0.79191178, -0.73598007,  1.90394328],
       [-0.92208056,  0.10267454, -0.01878275, -0.73598007,  1.90394328],
       [ 0.11926199,  1.14192509,  0.7525555 ,  1.35873244, -0.52522573],
       [ 0.28742892,  1.13183802, -1.59201133,  1.35873244, -0.52522573],
       [ 1.06049676, -0.6121584 ,  0.79357703, -0.73598007, -0.52522573],
       [-0.71486734, -1.61172739, -0.22315411, -0.73598007, -0.52522573],
       [-1.49480135, -0.33454072,  0.73203953, -0.73598007,  1.90394328],
       [ 1.5010591 , -0.22346159,  1.4054039 ,  1.35873244, -0.52522573],
       [ 0.8759735 ,  0.48549423,  2.09831813,  1.35873244, -0.52522573],
       [-1.52234937,  0.42827971, -1.59201133, -0.73598007, -0.52522573],
       [-1.05790906,  1.1820956 , -1.3703751 , -0.73598007, -0.52522573]])

In [28]:
x_test_scaled=scaler.transform(xtest)

In [31]:
x_test_scaled

array([[-0.13911607,  2.26499766, -0.66784754, -0.73598007,  1.90394328],
       [ 0.58589594, -1.26909222,  0.36150866, -0.73598007, -0.52522573],
       [ 0.61188715, -0.53767077,  0.20050224, -0.73598007,  1.90394328],
       [-0.93822328, -1.54448493, -0.30550951, -0.73598007,  1.90394328],
       [ 1.69098177, -0.90520232,  1.59888223, -0.73598007,  1.90394328],
       [-0.01229126,  0.13411747,  1.17061805,  1.35873244, -0.52522573],
       [-1.09870669, -2.27432478, -0.14285428,  1.35873244, -0.52522573],
       [-0.24204762,  1.10024533, -0.90196194,  1.35873244, -0.52522573],
       [ 0.02722495, -0.06355517,  0.78057393, -0.73598007,  1.90394328],
       [ 1.45362461, -1.28460636,  1.27218461, -0.73598007,  1.90394328],
       [-0.36020988, -0.83083138,  0.08687772, -0.73598007,  1.90394328],
       [-0.55873604, -1.53138909,  0.01556256,  1.35873244, -0.52522573],
       [ 0.05516772,  0.76704607, -0.54346196, -0.73598007,  1.90394328]])

In [33]:
regressior= LinearRegression()

In [38]:
regressior.fit(x_train_scaled,ytrain)

LinearRegression()

In [42]:
pred=regressior.predict(x_test_scaled)

In [43]:
pred

array([103555.29509993, 127893.49030828, 126714.99362961,  70591.00317675,
       173361.1879925 , 124193.80823935,  69279.72074976,  98431.321627  ,
       116413.4601948 , 161417.88839839,  94752.77404203,  89904.95586107,
       106002.57512499])

In [45]:
score=r2_score(ytest,pred)

In [46]:
score

0.883434366194034